---
- name: Run a test
  hosts: new_prime_client
  gather_facts: no
  vars:
    folder_name: Spec2020
    fg_mount: /mnt/freenas/test1
    client_mountpoints: ""
    username: spec
    password: SPEC2022
    benchmark: EDA_BLENDED
    load: 10
    incr_load: 10
    num_runs: 2
  tasks:
    - name: create mount_points
      set_fact: 
        client_mountpoints: "{{ client_mountpoints }} {{ item }}:{{ fg_mount }}"
      loop: "{{ groups['client_servers'] }}"
    - name: Create a variable file based on options passed in
      template:
        src: ./sfs_rc.j2
        dest: "/home/{{ username }}/{{ folder_name }}/SPECstorage2020/sfs_rc"
        lstrip_blocks: yes
    - name:
      set_fact:
        suffix: "{{ EDA_BLENDED }}-load-{{ load }}-increment-{{ incr_load }}-runs-{{ num_runs }}"
    - name: Run SPEC
      ansible.builtin.shell: "python3 SM2020 -r sfs_rc -s {{ suffix }}"
      args:
        chdir: "/home/{{ username }}/{{ folder_name }}/SPECstorage2020/"
      become_user: spec
      become: yes
      async: 86400
      poll: 15
      remote_user: spec