---
- hosts: new_clients
  gather_facts: yes
  vars:
#    ansible_python_interpreter: /root/anaconda3/bin/python3
    spec_filename: SPECstorage2020_2529.tar     # The name of your SPECstorage2020 tar file
    spec_location: /home/Schmitt/               # The folder of your SPECstorage2020 tar file
    folder_name: Spec2020                       # The name of the folder will contain your SPECstorage2020 packages and folders
    username: spec
    key_file: ~/.ssh/id_rsa                     # The ssh key you want to copy to your hosts
    nfs_storage_mount_options: hard,rsize=262144,wsize=262144,nconnect=16,vers=3,tcp    # Your nfs mounting options
    local_nfs_share_location: /mnt/freenas      # The location to mount your FlexGroup on your servers
  roles:
    - spec_deploy
