---
- name: Get node info
  netapp.ontap.na_ontap_info: 
    state: info
    hostname: "{{ inventory_hostname }}"
    username: "{{ ntap_username }}"
    password: "{{ ntap_password }}"
    gather_subset: "cluster_node_info"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  register: ontap_info
  connection: local
- name: Node info
  set_fact:
    node_list: "{{ ontap_info.ontap_info.cluster_node_info.keys() | list | sort }}"
- name: Output node info
  debug:
    var: node_list
