---
- name: Delete vserver
  netapp.ontap.na_ontap_svm:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local


