---
- name: debug ips
  debug:
    msg: "{{ hostvars[item]['ansible_facts'].default_ipv4.address }}"
  loop: "{{ groups['clients'] }}"
- name: debug ips
  debug:
    msg: "{{ hostvars[item].ansible_default_ipv4.address }}"
  loop: "{{ groups['clients'] }}"
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_facts.default_ipv4.address }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_nodename }}"
    state: present
  loop: "{{ groups['clients'] }}"