---
- name: Create Aggregates 
  netapp.ontap.na_ontap_aggregate:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    service_state: "{{ item.service_state }}"
    disk_count: "{{ item.disk_count }}"
    wait_for_online: yes
    time_out: 300
    snaplock_type: "{{ item.snaplock_type }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local
