---
- name: Create FCP
  netapp.ontap.na_ontap_fcp:
    state: "{{ item.state }}"
    status: up
    vserver: "{{ item.name }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local
