---
- name: Create LUN mapping
  netapp.ontap.na_ontap_lun_map:
    state: "{{ item.state }}"
    initiator_group_name: "{{ item.igroup }}"
    path: "{{ item.path }}"
    vserver: "{{ item.vserver }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local