---
- name: Create volume
  netapp.ontap.na_ontap_volume:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    aggregate_name: "{{ item.aggr_name }}"
    size: "{{ item.size }}"
    size_unit: "{{ item.size_unit }}"
    vserver: "{{ item.vserver }}"
    snapshot_policy: "{{ item.snapshot_policy }}"
    qos_policy_group: "{{ item.qos_policy_group }}"
    wait_for_completion: True
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local
